spring:
  application:
    name: biscato_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/biscato
    username: postgres
    password: 2200120
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
